# Generated by Django 2.0.4 on 2018-04-14 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 14, 18, 39, 36, 531416, tzinfo=utc), verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 14, 18, 39, 36, 531416, tzinfo=utc), verbose_name='Start Date'),
        ),
    ]
