# Generated by Django 2.0.4 on 2018-04-14 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 14, 18, 39, 36, 546417, tzinfo=utc)),
        ),
    ]
